# ============================
# Map Server Configuration
# ============================
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/opt/ros/humble/share/turtlebot3_navigation2/maps/map.yaml"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    controller_plugins: ["SicnavController"]

    SicnavController:
      plugin: "sicnav_controller::Controller"
      python_module: "sicnav_controller.controller"
      python_class: "Controller"
      max_speed: 0.4
      safety_margin: 0.3

